---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: EC2 instance
    amazon.aws.ec2_instance:
      region: us-west-2
      name: JVS_EC2
      vpc_subnet_id: subnet-0f20e2da734e0c181
      instance_type: t2.micro
      security_group: sg-051369b822723b4e8
      key_name: JVS_KEY
      image_id: ami-0db245b76e5c21ca1
      network:
        assign_public_ip: true
